version: '3.3'

networks:
  net:
    
services:
  web0:
    image: 'my_web:latest'
    container_name: web0
    ports:
      - '80:80'
      # - '8080:8080'
    entrypoint: /opt/runner.bash
    networks: 
      net:
        # aliases: 
        #   - web0
    # links:
    #   - web1
    # depends_on:
    #   - web1
    stdin_open: true
    tty: true

  web1:
    image: 'my_web:latest'
    container_name: web1
    ports:
      - 81:80
    entrypoint: /opt/runner.bash
    networks: 
      net:
        # aliases: 
        #   - web1
    # depends_on:
    #   - web0
    # links:
    #   - web0
    stdin_open: true
    tty: true
